export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  SELF_TRANSFER = 'SELF_TRANSFER',
  MISSING_FIELD = 'MISSING_FIELD',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  TRANSFER_NOT_FOUND = 'TRANSFER_NOT_FOUND',
}
